version: '3.8'

services:
  app:
    build: .
    ports:
      - "80:80"
    environment:
      - VITE_TMDB_API_KEY=${VITE_TMDB_API_KEY}
      - VITE_TMDB_ACCESS_TOKEN=${VITE_TMDB_ACCESS_TOKEN}
      - VITE_BRANDFETCH_API_KEY=${VITE_BRANDFETCH_API_KEY}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3